# -*- coding: utf-8 -*-
"""Text-to-Speech Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lssB80OPDXE8mBxR_NsCx_N8cc_mDJn
"""

!pip install TTS

!pip install gradio

"""Basic Text-to-Speech using Coqui TTS

Add Text Input + Audio Output

Add Gradio UI
"""

import gradio as gr
from TTS.api import TTS

tts = TTS(model_name="tts_models/en/ljspeech/tacotron2-DDC", progress_bar=False, gpu=False)

def generate_tts(text):
    output_path = "output.wav"
    tts.tts_to_file(text=text, file_path=output_path)
    return output_path

custom_title = "<h1 style='font-size: 38px'>Text-to-Speech Generator</h1>"
custom_description = """
<p style='font-size: 20px;'>
Explore how text-to-speech technology works!<br>
Type in a sentence and hear it spoken by an AI voice model.<br>
Enter text. Get speech. That simple.
</p>
"""

interface = gr.Interface(
    fn=generate_tts,
    inputs=gr.Textbox(label="Enter text", placeholder="Type something to speak...", lines=3),
    outputs=gr.Audio(label="Generated Speech"),
    title=custom_title,
    description=custom_description
)


interface.launch()